#!/usr/bin/env python3
"""harness sync - generate each tool's native config from the canonical source.
Generated files carry a DO-NOT-EDIT header. Idempotent: running twice changes nothing."""
import json, pathlib, sys

H = pathlib.Path.home() / ".harness"
HOME = pathlib.Path.home()
BANNER = "GENERATED by ~/.harness/sync.py - DO NOT EDIT. Edit the canonical source and re-run `harness sync`."
TARGETS = {
    "claude":   HOME / ".claude",
    "opencode": HOME / ".config" / "opencode",
    "codex":    HOME / ".codex",
    # opencode loads skills from the SHARED dir, not from its own config dir. Generated opencode
    # agents reference skills by name, so any skill they cite must land here or the reference
    # dangles (caught live: networking cited confluent-networking, which opencode could not load).
    "shared":   HOME / ".agents",
}

def agents():
    return [json.loads(p.read_text()) for p in sorted((H / "agents").glob("*.json"))]

def want(a, tool):
    only = a.get("only")
    return (tool in only) if only else True

def yaml_frontmatter(a):
    out = ["---", f"name: {a['name']}", f"description: {a['description']}"]
    if a.get("model"): out.append(f"model: {a['model']}")
    if a.get("tools"): out.append(f"tools: {a['tools']}")
    out += [f"# {BANNER}", "---", ""]
    return "\n".join(out)

def gen_md(a, tool):
    """Each tool has its own frontmatter schema. opencode uses `permission:` maps and its own
    model namespace, Claude uses `tools:`/`model:`. Use the captured per-tool frontmatter when
    we have it, so generation never invents a shape the tool will reject."""
    ov = (a.get("overrides") or {}).get(f"{tool}_frontmatter")
    if ov:
        fm = "---\n" + ov.rstrip() + f"\n# {BANNER}\n---\n\n"
        return fm + a["body"].rstrip() + "\n"
    return yaml_frontmatter(a) + a["body"].rstrip() + "\n"

def toml_basic_string(s):
    """TOML basic string: escape backslash and double quote, collapse newlines."""
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return s.replace("\n", " ").strip()

def gen_toml(a):
    """Codex requires `developer_instructions`; a role file using `instructions` is silently
    rejected with "must define developer_instructions" and the agent simply does not exist.
    Verified live: all 18 generated roles were being ignored. Codex takes no `model` key.
    The body goes in a literal (single-quote) block so backslashes pass through unchanged.
    """
    body = a["body"].rstrip().replace("'''", "'' '")   # a literal block cannot contain '''
    return (f"# {BANNER}\n"
            f'name = "{toml_basic_string(a["name"])}"\n'
            f'description = "{toml_basic_string(a["description"])}"\n'
            f"developer_instructions = '''\n{body}\n'''\n")

def write(path, content, dry):
    """content may be str or bytes; binary assets in skills must survive."""
    path.parent.mkdir(parents=True, exist_ok=True)
    b = content.encode() if isinstance(content, str) else content
    old = path.read_bytes() if path.exists() else None
    if old == b: return "same"
    if not dry: path.write_bytes(b)
    return "new" if old is None else "changed"

def main():
    dry = "--dry-run" in sys.argv
    counts = {}
    for a in agents():
        for tool, root in TARGETS.items():
            if not want(a, tool): continue
            if tool == "codex":
                r = write(root / "agents" / f"{a['name']}.toml", gen_toml(a), dry)
            else:
                r = write(root / "agents" / f"{a['name']}.md", gen_md(a, tool), dry)
            counts[f"{tool}:{r}"] = counts.get(f"{tool}:{r}", 0) + 1
    # instructions
    ci = H / "instructions" / "CLAUDE.md"
    ai = H / "instructions" / "AGENTS.md"
    if ci.exists(): counts["claude:CLAUDE.md"] = write(TARGETS["claude"] / "CLAUDE.md", ci.read_text(), dry)
    if ai.exists():
        counts["opencode:AGENTS.md"] = write(TARGETS["opencode"] / "AGENTS.md", ai.read_text(), dry)
        counts["home:AGENTS.md"] = write(HOME / "AGENTS.md", ai.read_text(), dry)
    # skills + rules + hooks: copy trees verbatim
    for kind, dests in (("skills", ["claude", "shared"]), ("rules", ["claude"]), ("hooks", ["claude"])):
        srcd = H / kind
        if not srcd.exists(): continue
        for tool in dests:
            for p in srcd.rglob("*"):
                if p.is_file():
                    rel = p.relative_to(srcd)
                    # `synced/` is Claude Code's per-account skill cache; its paths carry org ids
                    # and the tool re-creates it. It must never reach the shared dir or a repo.
                    if rel.parts and rel.parts[0] == "synced":
                        continue
                    r = write(TARGETS[tool] / kind / rel, p.read_bytes(), dry)
                    counts[f"{tool}:{kind}:{r}"] = counts.get(f"{tool}:{kind}:{r}", 0) + 1
    print(("DRY RUN " if dry else "") + "sync result: " + json.dumps(counts, indent=2, default=str))

if __name__ == "__main__":
    main()
